version: '3.11'


services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./ops/environment/.default.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./ops/environment/.postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d TeamerDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


networks:
  web_network:

volumes:
  postgres_data:
